mod 'chocolatey-chocolatey', '1.2.6'
mod 'puppetlabs-stdlib', '4.14.0'
mod 'puppet-archive', '1.1.2'
mod 'puppet-staging', '2.0.1'
mod 'AlexCline-dirtree', '0.2.1'
mod 'badgerious-windows_env', '2.2.2'